// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAamgGnZ_8ZL10LauRqFW70EayCxWNBZG4',
    appId: '1:934562816321:web:3b4c0d58650f1ec1a081c0',
    messagingSenderId: '934562816321',
    projectId: 'fireship-course-quizzapp',
    authDomain: 'fireship-course-quizzapp.firebaseapp.com',
    storageBucket: 'fireship-course-quizzapp.appspot.com',
    measurementId: 'G-HF4HR6YH61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdjqwpx9_hJtAly9j6nZb2Has8Z3HihVk',
    appId: '1:934562816321:android:835bcda4630f0de3a081c0',
    messagingSenderId: '934562816321',
    projectId: 'fireship-course-quizzapp',
    storageBucket: 'fireship-course-quizzapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGdFJLDLhXlMluX0yLJtesjbbx1Mb9b8w',
    appId: '1:934562816321:ios:e20258313121bd4fa081c0',
    messagingSenderId: '934562816321',
    projectId: 'fireship-course-quizzapp',
    storageBucket: 'fireship-course-quizzapp.appspot.com',
    androidClientId: '934562816321-ngapanlnd519262hguo0na5urs884q0r.apps.googleusercontent.com',
    iosClientId: '934562816321-b7fee8jh7co8aur44vt94psft7kpgjq2.apps.googleusercontent.com',
    iosBundleId: 'io.barsan.quizzapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGdFJLDLhXlMluX0yLJtesjbbx1Mb9b8w',
    appId: '1:934562816321:ios:e20258313121bd4fa081c0',
    messagingSenderId: '934562816321',
    projectId: 'fireship-course-quizzapp',
    storageBucket: 'fireship-course-quizzapp.appspot.com',
    androidClientId: '934562816321-ngapanlnd519262hguo0na5urs884q0r.apps.googleusercontent.com',
    iosClientId: '934562816321-b7fee8jh7co8aur44vt94psft7kpgjq2.apps.googleusercontent.com',
    iosBundleId: 'io.barsan.quizzapp',
  );
}
